export const demoCategories = [
  {
    name: "Kurtis",
    slug: "kurtis",
    description: "Elegant everyday and occasion kurtis with refined detailing.",
    image: "/category-images/kurti.jpg",
    sortOrder: 1,
    featured: true,
  },
  {
    name: "Blouses",
    slug: "blouses",
    description: "Statement blouse designs tailored for Indian silhouettes.",
    image: "/category-images/blouse.jpg",
    sortOrder: 2,
    featured: true,
  },
  {
    name: "Dresses",
    slug: "dresses",
    description: "Minimal dresses with a premium fashion-forward finish.",
    image: "/category-images/dress.jpg",
    sortOrder: 3,
    featured: true,
  },
  {
    name: "Co-ord Sets",
    slug: "co-ord-sets",
    description: "Stylish matching sets for modern everyday dressing.",
    image: "/category-images/coord-set.jpg",
    sortOrder: 4,
    featured: true,
  },
  {
    name: "Lehengas",
    slug: "lehengas",
    description: "Occasion-ready lehengas with bridal and festive appeal.",
    image: "/category-images/lehenga.jpg",
    sortOrder: 5,
    featured: true,
  },
];

export const demoCollections = [
  {
    name: "New Arrivals",
    slug: "new-arrivals",
    description: "Freshly launched premium pieces.",
    featured: true,
    status: "active" as const,
    heroImage: "/category-images/kurti.jpg",
  },
  {
    name: "Festive Edit",
    slug: "festive-edit",
    description: "Rich colors and celebration-ready outfits.",
    featured: true,
    status: "active" as const,
    heroImage: "/category-images/ethnic-wear.jpg",
  },
  {
    name: "Wedding Collection",
    slug: "wedding-collection",
    description: "Statement garments for weddings and special events.",
    featured: true,
    status: "active" as const,
    heroImage: "/category-images/lehenga.jpg",
  },
  {
    name: "Editor’s Picks",
    slug: "editors-picks",
    description: "Handpicked looks curated by the atelier team.",
    featured: true,
    status: "active" as const,
    heroImage: "/category-images/dress.jpg",
  },
];

export const demoProducts = [
  {
    name: "Floral Printed A-Line Kurti",
    slug: "floral-printed-a-line-kurti",
    sku: "KUR-1001",
    categorySlug: "kurtis",
    collectionSlug: "new-arrivals",
    brand: "Divya & Design",
    description:
      "A graceful A-line kurti with soft floral print, premium fabric, and a flattering fall.",
    shortDescription: "Soft floral A-line kurti in a premium finish.",
    highlights: [
      "Lightweight feel",
      "Flattering A-line shape",
      "Day-to-evening styling",
    ],
    fabric: "Cotton Silk",
    careInstructions: "Dry clean recommended",
    occasion: "Casual",
    color: "Rose",
    pattern: "Floral",
    material: "Cotton Silk",
    fit: "Regular",
    countryOfOrigin: "India",
    tags: ["new", "floral", "kurti"],
    pricing: { mrp: 1899, sellingPrice: 1499, discountPercent: 21 },
    inventory: { stock: 12, trackInventory: true, lowStockAlert: 4, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/kurti.jpg",
        alt: "Floral printed A-line kurti",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Embroidered Straight Kurti",
    slug: "embroidered-straight-kurti",
    sku: "KUR-1002",
    categorySlug: "kurtis",
    collectionSlug: "festive-edit",
    brand: "Divya & Design",
    description:
      "A straight kurti with elegant embroidery and a refined festive look.",
    shortDescription: "Festive straight kurti with embroidery.",
    highlights: ["Embroidery detail", "Clean silhouette", "Premium festive style"],
    fabric: "Chanderi",
    careInstructions: "Hand wash separately",
    occasion: "Festive",
    color: "Gold",
    pattern: "Embroidered",
    material: "Chanderi",
    fit: "Regular",
    countryOfOrigin: "India",
    tags: ["festive", "embroidered", "kurti"],
    pricing: { mrp: 2199, sellingPrice: 1699, discountPercent: 23 },
    inventory: { stock: 8, trackInventory: true, lowStockAlert: 3, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/ethnic-wear.jpg",
        alt: "Embroidered straight kurti",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Chikankari Kurti Set",
    slug: "chikankari-kurti-set",
    sku: "KUR-1003",
    categorySlug: "kurtis",
    collectionSlug: "editors-picks",
    brand: "Divya & Design",
    description:
      "A soft chikankari set that blends comfort, elegance, and timeless craftsmanship.",
    shortDescription: "Classic chikankari set in ivory tones.",
    highlights: ["Chikankari work", "Elegant set", "Everyday premium wear"],
    fabric: "Mulmul",
    careInstructions: "Gentle machine wash",
    occasion: "Daily Wear",
    color: "Ivory",
    pattern: "Chikankari",
    material: "Cotton",
    fit: "Relaxed",
    countryOfOrigin: "India",
    tags: ["ivory", "chikankari", "set"],
    pricing: { mrp: 2599, sellingPrice: 2199, discountPercent: 15 },
    inventory: { stock: 10, trackInventory: true, lowStockAlert: 5, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/kurti.jpg",
        alt: "Chikankari kurti set",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Mirror Work Co-ord Set",
    slug: "mirror-work-coord-set",
    sku: "CRD-1004",
    categorySlug: "co-ord-sets",
    collectionSlug: "new-arrivals",
    brand: "Divya & Design",
    description:
      "A contemporary co-ord set with mirror work accents and a polished silhouette.",
    shortDescription: "Mirror work co-ord set with a tailored finish.",
    highlights: ["Co-ord styling", "Mirror accents", "Occasion-ready"],
    fabric: "Modal Satin",
    careInstructions: "Dry clean only",
    occasion: "Party",
    color: "Slate",
    pattern: "Solid",
    material: "Modal",
    fit: "Tailored",
    countryOfOrigin: "India",
    tags: ["coord", "mirror-work", "modern"],
    pricing: { mrp: 2999, sellingPrice: 2499, discountPercent: 17 },
    inventory: { stock: 6, trackInventory: true, lowStockAlert: 2, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/coord-set.jpg",
        alt: "Mirror work co-ord set",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Designer Lehenga",
    slug: "designer-lehenga",
    sku: "LEH-1005",
    categorySlug: "lehengas",
    collectionSlug: "wedding-collection",
    brand: "Divya & Design",
    description:
      "A rich designer lehenga with festive embroidery and statement drape.",
    shortDescription: "Wedding lehenga with a luxurious festive finish.",
    highlights: ["Wedding-ready", "Rich color story", "Premium drape"],
    fabric: "Silk Blend",
    careInstructions: "Dry clean only",
    occasion: "Wedding",
    color: "Wine",
    pattern: "Embroidered",
    material: "Silk Blend",
    fit: "Classic",
    countryOfOrigin: "India",
    tags: ["wedding", "lehenga", "luxury"],
    pricing: { mrp: 7999, sellingPrice: 6999, discountPercent: 13 },
    inventory: { stock: 4, trackInventory: true, lowStockAlert: 2, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/lehenga.jpg",
        alt: "Designer bridal lehenga",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Pastel Shirt Dress",
    slug: "pastel-shirt-dress",
    sku: "DRS-1006",
    categorySlug: "dresses",
    collectionSlug: "editors-picks",
    brand: "Divya & Design",
    description:
      "A breezy shirt dress with a modern pastel palette and effortless comfort.",
    shortDescription: "Soft pastel dress for everyday luxury.",
    highlights: ["Comfort first", "Minimal styling", "Modern silhouette"],
    fabric: "Linen Blend",
    careInstructions: "Cold wash",
    occasion: "Casual",
    color: "Blush",
    pattern: "Solid",
    material: "Linen Blend",
    fit: "Relaxed",
    countryOfOrigin: "India",
    tags: ["dress", "pastel", "minimal"],
    pricing: { mrp: 2399, sellingPrice: 1899, discountPercent: 21 },
    inventory: { stock: 15, trackInventory: true, lowStockAlert: 6, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: false },
    images: [
      {
        url: "/category-images/dress.jpg",
        alt: "Pastel shirt dress",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Ivory Occasion Dress",
    slug: "ivory-occasion-dress",
    sku: "DRS-1007",
    categorySlug: "dresses",
    collectionSlug: "festive-edit",
    brand: "Divya & Design",
    description:
      "An ivory occasion dress designed for elegant functions and intimate celebrations.",
    shortDescription: "Occasion dress with a soft premium finish.",
    highlights: ["Occasion-ready", "Elegant drape", "Premium finish"],
    fabric: "Georgette",
    careInstructions: "Dry clean preferred",
    occasion: "Occasion",
    color: "Ivory",
    pattern: "Solid",
    material: "Georgette",
    fit: "Slim",
    countryOfOrigin: "India",
    tags: ["dress", "occasion", "ivory"],
    pricing: { mrp: 2799, sellingPrice: 2299, discountPercent: 18 },
    inventory: { stock: 7, trackInventory: true, lowStockAlert: 3, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: false },
    images: [
      {
        url: "/category-images/dress.jpg",
        alt: "Ivory occasion dress",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
  {
    name: "Royal Blouse",
    slug: "royal-blouse",
    sku: "BLS-1008",
    categorySlug: "blouses",
    collectionSlug: "wedding-collection",
    brand: "Divya & Design",
    description:
      "A royal blouse with tailored fit, elegant neckline, and festive glamour.",
    shortDescription: "Blouse for statement festive looks.",
    highlights: ["Statement neckline", "Tailored fit", "Pair with lehengas"],
    fabric: "Raw Silk",
    careInstructions: "Dry clean only",
    occasion: "Wedding",
    color: "Plum",
    pattern: "Embroidered",
    material: "Raw Silk",
    fit: "Tailored",
    countryOfOrigin: "India",
    tags: ["blouse", "royal", "festive"],
    pricing: { mrp: 1799, sellingPrice: 1499, discountPercent: 17 },
    inventory: { stock: 9, trackInventory: true, lowStockAlert: 4, unlimitedStock: false, backorder: false },
    status: "active" as const,
    visibility: "public" as const,
    customization: { enabled: true },
    images: [
      {
        url: "/category-images/blouse.jpg",
        alt: "Royal silk blouse",
        type: "image" as const,
        isPrimary: true,
        sortOrder: 0,
      },
    ],
  },
] as const;

export const demoOrders = [
  {
    orderId: "ORD-1001",
    customerName: "Ayesha Khan",
    email: "ayesha@example.com",
    phone: "9876500001",
    status: "processing" as const,
    paymentMethod: "Razorpay",
    shippingMethod: "Standard Shipping",
    notes: "Add a note card for gifting.",
    items: [
      {
        name: "Floral Printed A-Line Kurti",
        sku: "KUR-1001",
        quantity: 1,
        price: 1499,
        customization: {},
      },
    ],
    totals: { subtotal: 1499, shipping: 99, discount: 0, tax: 0, grandTotal: 1598 },
    timeline: [{ status: "processing", note: "Stitching in progress", at: new Date().toISOString() }],
  },
  {
    orderId: "ORD-1002",
    customerName: "Meera Joshi",
    email: "meera@example.com",
    phone: "9876500002",
    status: "shipped" as const,
    paymentMethod: "Cashfree",
    shippingMethod: "Express Shipping",
    items: [
      {
        name: "Designer Lehenga",
        sku: "LEH-1005",
        quantity: 1,
        price: 6999,
        customization: {},
      },
    ],
    totals: { subtotal: 6999, shipping: 199, discount: 0, tax: 0, grandTotal: 7198 },
    timeline: [{ status: "shipped", note: "Dispatched to courier", at: new Date().toISOString() }],
  },
];

export const demoUsers = [
  {
    name: "Divya Admin",
    email: "admin@divyaanddesign.com",
    password: "Admin@12345!",
    role: "admin" as const,
    emailVerifiedAt: new Date(),
  },
  {
    name: "Demo Customer",
    email: "customer@divyaanddesign.com",
    password: "Customer@12345!",
    role: "customer" as const,
    emailVerifiedAt: new Date(),
  },
];
